create table if not exists public.core_outputs (
  id bigint generated by default as identity primary key,
  idea_title text not null,
  idea_description text not null,
  target_user text not null,
  core_idea text not null,
  core_problem text not null,
  core_user text not null,
  core_value text not null,
  next_step text not null,
  created_at timestamptz not null default now()
);

alter table public.core_outputs enable row level security;

create policy "Public can read core outputs"
on public.core_outputs
for select
to anon
using (true);

create policy "Public can insert core outputs"
on public.core_outputs
for insert
to anon
with check (true);
