create table if not exists public.company_emissions (
  id bigint generated by default as identity primary key,
  ticker text not null,
  company_name text not null,
  reporting_year integer not null check (reporting_year between 2000 and 2100),
  scope_1_tco2e numeric not null check (scope_1_tco2e >= 0),
  scope_2_tco2e numeric not null check (scope_2_tco2e >= 0),
  source_name text not null,
  source_url text not null,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  unique (ticker, reporting_year)
);

alter table public.company_emissions enable row level security;

create policy "Public can read emissions"
on public.company_emissions
for select
to anon
using (true);

comment on table public.company_emissions is
'Annual company emissions manually transcribed from official sustainability reports.';
